######################################################################
# Automatically generated by qmake (3.1) Tue May 8 23:11:27 2018
######################################################################

TEMPLATE = app
TARGET = Debug/test
INCLUDEPATH += . ../core
QT += widgets opengl printsupport
CONFIG += debug
QMAKE_CXXFLAGS += -fopenmp -std=c++11
QMAKE_LFLAGS += -fopenmp

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += ../core/zbasescene.h ../core/zbaseview.h
SOURCES += main.cpp ../core/zbasescene.cpp ../core/zbaseview.cpp

RESOURCES += images.qrc

HEADERS += mainwindow.h view.h chip.h
SOURCES += mainwindow.cpp view.cpp chip.cpp
